
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Play extends javax.swing.JFrame {

    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
        ImageIcon icon =new ImageIcon("D:\\netproject\\Task_2\\src\\main\\java\\Images\\plain.jpg");
        Image img=icon.getImage();
        Image image =img.getScaledInstance(bglabel.getWidth(),bglabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgicon=new ImageIcon(image);
        bglabel.setIcon(imgicon);
        
        ImageIcon icon1 =new ImageIcon("D:\\netproject\\Task_2\\src\\main\\java\\Images\\hint.png");
        Image img1=icon1.getImage();
        Image image1 =img1.getScaledInstance(hint.getWidth(),hint.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgicon1=new ImageIcon(image1);
        hint.setIcon(imgicon1);
    }
    Play(String name)
    {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        this();
        namelabel.setText(name.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomelabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numbertextfield = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        hint = new javax.swing.JLabel();
        chance = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        snum = new javax.swing.JLabel();
        cnum = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        bglabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomelabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomelabel.setText("WELCOME TO NUMBER GUESSING GAME :");
        jPanel1.add(welcomelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 490, 40));

        namelabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 270, 40));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER THE NUMBER BETWEEN 1 - 100");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 470, 40));

        numbertextfield.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        numbertextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numbertextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbertextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(numbertextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 470, 50));

        submit.setBackground(new java.awt.Color(0, 204, 0));
        submit.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 160, -1));

        hint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hintMouseClicked(evt);
            }
        });
        jPanel1.add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 40, 50));

        chance.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        chance.setForeground(new java.awt.Color(255, 255, 255));
        chance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chance.setText("SCORE :");
        jPanel1.add(chance, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, 30));

        score.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText(" CHANCE :");
        jPanel1.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        snum.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        snum.setForeground(new java.awt.Color(255, 255, 255));
        snum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snum.setText("100");
        jPanel1.add(snum, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 40, 30));

        cnum.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        cnum.setForeground(new java.awt.Color(255, 255, 255));
        cnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cnum.setText("5");
        jPanel1.add(cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 40, 30));

        message.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 640, 40));
        jPanel1.add(bglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numbertextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbertextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbertextfieldActionPerformed

    private void hintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hintMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, random);
    }//GEN-LAST:event_hintMouseClicked
         Random rand = new Random();
         int random = rand.nextInt(100) + 1;
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        while(Integer.parseInt(cnum.getText()) != 0)
        {
            if(Integer.parseInt(numbertextfield.getText()) == random)
            {
                
                snum.setText(""+(Integer.parseInt(snum.getText())+100));
                String name=namelabel.getText();
                int limit=Integer.parseInt(cnum.getText());
                int mark=Integer.parseInt(snum.getText());
                Score sc=new Score(name,limit,mark);
                sc.show();
                this.hide();
                break;
                 
                
            }
            else if(Integer.parseInt(numbertextfield.getText()) > random)
            {
                 message.setText("Oh No! your guess is too high");
                 snum.setText(""+(Integer.parseInt(snum.getText())-10));
                 cnum.setText(""+(Integer.parseInt(cnum.getText())-1));
                 numbertextfield.setText("");
            }
            else if(Integer.parseInt(numbertextfield.getText()) < random)
            {
                 message.setText("Oh No! your guess is too low");
                 snum.setText(""+(Integer.parseInt(snum.getText())-10));
                 cnum.setText(""+(Integer.parseInt(cnum.getText())-1));
                 numbertextfield.setText("");
            }
        }
        if(Integer.parseInt(cnum.getText())== 0)
        {
            String name=namelabel.getText();
            int limit=Integer.parseInt(cnum.getText());
            int mark=Integer.parseInt(snum.getText());
            Score sc=new Score(name,limit,mark);
            sc.show();
            this.hide();
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bglabel;
    private javax.swing.JLabel chance;
    private javax.swing.JLabel cnum;
    private javax.swing.JLabel hint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField numbertextfield;
    private javax.swing.JLabel score;
    private javax.swing.JLabel snum;
    private javax.swing.JButton submit;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
