
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        ImageIcon icon =new ImageIcon("D:\\netproject\\Task_2\\src\\main\\java\\Images\\quest.jpg");
        Image img=icon.getImage();
        Image image =img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgicon=new ImageIcon(image);
        jLabel1.setIcon(imgicon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        Namelabel = new javax.swing.JLabel();
        nametextfield = new javax.swing.JTextField();
        startbutton = new javax.swing.JButton();
        instructbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("NUMBER GUESSING GAME");
        jPanel1.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 660, 50));

        Namelabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        Namelabel.setForeground(new java.awt.Color(255, 255, 255));
        Namelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Namelabel.setText("ENTER THE NAME");
        jPanel1.add(Namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 156, 300, 40));

        nametextfield.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        nametextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(nametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 350, 40));

        startbutton.setBackground(new java.awt.Color(0, 204, 0));
        startbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        startbutton.setText("LET'S GO...");
        startbutton.setName(""); // NOI18N
        startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(startbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 40));

        instructbutton.setBackground(new java.awt.Color(255, 255, 102));
        instructbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        instructbutton.setText("INSTRUCTIONs");
        instructbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(instructbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 500, 160, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void instructbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructbuttonActionPerformed
        // TODO add your handling code here:
        Instruct inst=new Instruct();
        inst.show();
        this.hide();
    }//GEN-LAST:event_instructbuttonActionPerformed

    private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
        // TODO add your handling code here:
        String name=nametextfield.getText();
        new Play(name).setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_startbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Namelabel;
    private javax.swing.JLabel heading;
    private javax.swing.JButton instructbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametextfield;
    private javax.swing.JButton startbutton;
    // End of variables declaration//GEN-END:variables
}
